name: Waka Readme

on:
  workflow_dispatch: # 수동으로 워크플로우 실행 가능
  schedule:
    - cron: "0 0 * * *" # 매일 UTC 0시(한국 시간 오전 9시)에 실행

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_TIMEZONE: true
          SHOW_COMMIT: true
          SHOW_LANGUAGE: true
          SHOW_DAYS_OF_WEEK: true
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_SHORT_INFO: true
          SHOW_LOC_CHART: true
